### ISSUE TITLE
Apache Drill has issue with release 3.2.0

### ISSUE THREAD

**Issue by cgivre** [pjfanning/excel-streaming-reader#76] opened 2021-11-12 18:53 UTC
@pjfanning 
The latest release the streaming reader seems to have broken Drill.  When running queries against Excel files, we get the following error.

```
(java.lang.NoClassDefFoundError) Could not initialize class com.github.pjfanning.xlsx.impl.StreamingWorkbookReader
    com.github.pjfanning.xlsx.StreamingReader$Builder.open():372
    org.apache.drill.exec.store.excel.ExcelBatchReader.openFile():232
    org.apache.drill.exec.store.excel.ExcelBatchReader.open():196
    org.apache.drill.exec.store.excel.ExcelBatchReader.open():62
    org.apache.drill.exec.physical.impl.scan.framework.ManagedScanFramework.open():208
    org.apache.drill.exec.physical.impl.scan.file.FileScanFramework.open():276
    org.apache.drill.exec.physical.impl.scan.framework.ShimBatchReader.open():75
    org.apache.drill.exec.physical.impl.scan.ReaderState.open():229
    org.apache.drill.exec.physical.impl.scan.ScanOperatorExec.nextAction():273
    org.apache.drill.exec.physical.impl.scan.ScanOperatorExec.next():229
    org.apache.drill.exec.physical.impl.protocol.OperatorDriver.doNext():201
    org.apache.drill.exec.physical.impl.protocol.OperatorDriver.start():179
    org.apache.drill.exec.physical.impl.protocol.OperatorDriver.next():129
    org.apache.drill.exec.physical.impl.protocol.OperatorRecordBatch.next():149
    org.apache.drill.exec.record.AbstractRecordBatch.next():119
    org.apache.drill.exec.record.AbstractRecordBatch.next():111
    org.apache.drill.exec.record.AbstractUnaryRecordBatch.innerNext():59
    org.apache.drill.exec.physical.impl.limit.LimitRecordBatch.innerNext():93
    org.apache.drill.exec.record.AbstractRecordBatch.next():170
    org.apache.drill.exec.record.AbstractRecordBatch.next():119
    org.apache.drill.exec.record.AbstractRecordBatch.next():111
    org.apache.drill.exec.record.AbstractUnaryRecordBatch.innerNext():59
    org.apache.drill.exec.record.AbstractRecordBatch.next():170
    org.apache.drill.exec.record.AbstractRecordBatch.next():119
    org.apache.drill.exec.record.AbstractRecordBatch.next():111
    org.apache.drill.exec.record.AbstractUnaryRecordBatch.innerNext():59
    org.apache.drill.exec.physical.impl.project.ProjectRecordBatch.innerNext():85
    org.apache.drill.exec.record.AbstractRecordBatch.next():170
    org.apache.drill.exec.physical.impl.BaseRootExec.next():103
    org.apache.drill.exec.physical.impl.ScreenCreator$ScreenRoot.innerNext():81
    org.apache.drill.exec.physical.impl.BaseRootExec.next():93
    org.apache.drill.exec.work.fragment.FragmentExecutor$1.run():323
    org.apache.drill.exec.work.fragment.FragmentExecutor$1.run():310
    java.security.AccessController.doPrivileged():-2
    javax.security.auth.Subject.doAs():422
    org.apache.hadoop.security.UserGroupInformation.doAs():1762
    org.apache.drill.exec.work.fragment.FragmentExecutor.run():310
    org.apache.drill.common.SelfCleaningRunnable.run():38
    java.util.concurrent.ThreadPoolExecutor.runWorker():1149
    java.util.concurrent.ThreadPoolExecutor$Worker.run():624
    java.lang.Thread.run():748 (state=,code=0)
```

**Comment by pjfanning** [comment] 2021-11-12 19:10
@cgivre I don't think I'll be able to reproduce this issue based on that stack trace alone. When you say 'latest release', would it be possible to provide the actual version number to avoid any confusion?

**Comment by cgivre** [comment] 2021-11-12 19:12
@pjfanning 
Thanks for your quick response!  We're currently using 3.2.0.  I just noticed that you updated to 3.2.1, so I'm building with that.  Let me see if the latest version solves this.   
To reproduce however, simply d/l the latest snapshot of Drill and run a query against an Excel file and that error appears.

**Comment by pjfanning** [comment] 2021-11-12 19:14
I did the PR for Drill to upgrade to v3.2.0 and the unit tests passed fine. It seems odd that the unit tests should pass but the code then breaks in deployment.

**Comment by pjfanning** [comment] 2021-11-12 19:16
I see `org.apache.hadoop.security.UserGroupInformation` in the stack trace - if you running Drill on Hadoop, the classpath can be a real minefield - Hadoop brings lot of its own dependencies and these are often outdated.

**Comment by cgivre** [comment] 2021-11-12 19:17
That surprised me as well.  Usually if the unit tests pass, it works fine.  It's almost like the class isn't being built or included somehow.

**Comment by pjfanning** [comment] 2021-11-12 19:18
This is a `Could not initialize class` issue which usually a static initializer is failing.

**Comment by cgivre** [comment] 2021-11-12 19:20
Ok... upgraded to latest version and am now getting a slightly different error:
```
Error: EXECUTION_ERROR ERROR: org.apache.logging.log4j.util.Strings.isEmpty(Ljava/lang/CharSequence;)Z

Open failed for reader: ExcelBatchReader
Fragment: 0:0

[Error Id: f973040f-a7ad-4607-b3a7-334417350b20 on 192.168.1.37:31010]

  (java.lang.NoSuchMethodError) org.apache.logging.log4j.util.Strings.isEmpty(Ljava/lang/CharSequence;)Z
    org.apache.logging.log4j.status.StatusLogger.<init>():107
    org.apache.logging.log4j.status.StatusLogger.<clinit>():85
    org.apache.logging.log4j.LogManager.<clinit>():61
    org.apache.poi.util.XMLHelper.<clinit>():80
    com.github.pjfanning.xlsx.impl.StreamingWorkbookReader.<clinit>():49
    com.github.pjfanning.xlsx.StreamingReader$Builder.open():372
    org.apache.drill.exec.store.excel.ExcelBatchReader.openFile():232
    org.apache.drill.exec.store.excel.ExcelBatchReader.open():196
    org.apache.drill.exec.store.excel.ExcelBatchReader.open():62
```

**Comment by cgivre** [comment] 2021-11-12 19:21
Full stack trace:
```java
java.sql.SQLException: EXECUTION_ERROR ERROR: Could not initialize class com.github.pjfanning.xlsx.impl.StreamingWorkbookReader

Open failed for reader: ExcelBatchReader
Fragment: 0:0

[Error Id: 461ed38c-57ce-402e-b221-56d7da525f80 on 192.168.1.37:31010]

  (java.lang.NoClassDefFoundError) Could not initialize class com.github.pjfanning.xlsx.impl.StreamingWorkbookReader
    com.github.pjfanning.xlsx.StreamingReader$Builder.open():372
    org.apache.drill.exec.store.excel.ExcelBatchReader.openFile():232
    org.apache.drill.exec.store.excel.ExcelBatchReader.open():196
    org.apache.drill.exec.store.excel.ExcelBatchReader.open():62
    org.apache.drill.exec.physical.impl.scan.framework.ManagedScanFramework.open():208
    org.apache.drill.exec.physical.impl.scan.file.FileScanFramework.open():276
    org.apache.drill.exec.physical.impl.scan.framework.ShimBatchReader.open():75
    org.apache.drill.exec.physical.impl.scan.ReaderState.open():229
    org.apache.drill.exec.physical.impl.scan.ScanOperatorExec.nextAction():273
    org.apache.drill.exec.physical.impl.scan.ScanOperatorExec.next():229
    org.apache.drill.exec.physical.impl.protocol.OperatorDriver.doNext():201
    org.apache.drill.exec.physical.impl.protocol.OperatorDriver.start():179
    org.apache.drill.exec.physical.impl.protocol.OperatorDriver.next():129
    org.apache.drill.exec.physical.impl.protocol.OperatorRecordBatch.next():149
    org.apache.drill.exec.record.AbstractRecordBatch.next():119
    org.apache.drill.exec.record.AbstractRecordBatch.next():111
    org.apache.drill.exec.record.AbstractUnaryRecordBatch.innerNext():59
    org.apache.drill.exec.physical.impl.limit.LimitRecordBatch.innerNext():93
    org.apache.drill.exec.record.AbstractRecordBatch.next():170
    org.apache.drill.exec.record.AbstractRecordBatch.next():119
    org.apache.drill.exec.record.AbstractRecordBatch.next():111
    org.apache.drill.exec.record.AbstractUnaryRecordBatch.innerNext():59
    org.apache.drill.exec.record.AbstractRecordBatch.next():170
    org.apache.drill.exec.record.AbstractRecordBatch.next():119
    org.apache.drill.exec.record.AbstractRecordBatch.next():111
    org.apache.drill.exec.record.AbstractUnaryRecordBatch.innerNext():59
    org.apache.drill.exec.physical.impl.project.ProjectRecordBatch.innerNext():85
    org.apache.drill.exec.record.AbstractRecordBatch.next():170
    org.apache.drill.exec.physical.impl.BaseRootExec.next():103
    org.apache.drill.exec.physical.impl.ScreenCreator$ScreenRoot.innerNext():81
    org.apache.drill.exec.physical.impl.BaseRootExec.next():93
    org.apache.drill.exec.work.fragment.FragmentExecutor$1.run():323
    org.apache.drill.exec.work.fragment.FragmentExecutor$1.run():310
    java.security.AccessController.doPrivileged():-2
    javax.security.auth.Subject.doAs():422
    org.apache.hadoop.security.UserGroupInformation.doAs():1762
    org.apache.drill.exec.work.fragment.FragmentExecutor.run():310
    org.apache.drill.common.SelfCleaningRunnable.run():38
    java.util.concurrent.ThreadPoolExecutor.runWorker():1149
    java.util.concurrent.ThreadPoolExecutor$Worker.run():624
    java.lang.Thread.run():748

	at org.apache.drill.jdbc.impl.DrillCursor.nextRowInternally(DrillCursor.java:534)
	at org.apache.drill.jdbc.impl.DrillCursor.loadInitialSchema(DrillCursor.java:599)
	at org.apache.drill.jdbc.impl.DrillResultSetImpl.execute(DrillResultSetImpl.java:1278)
	at org.apache.drill.jdbc.impl.DrillResultSetImpl.execute(DrillResultSetImpl.java:58)
	at org.apache.calcite.avatica.AvaticaConnection$1.execute(AvaticaConnection.java:667)
	at org.apache.drill.jdbc.impl.DrillMetaImpl.prepareAndExecute(DrillMetaImpl.java:1102)
	at org.apache.drill.jdbc.impl.DrillMetaImpl.prepareAndExecute(DrillMetaImpl.java:1113)
	at org.apache.calcite.avatica.AvaticaConnection.prepareAndExecuteInternal(AvaticaConnection.java:675)
	at org.apache.drill.jdbc.impl.DrillConnectionImpl.prepareAndExecuteInternal(DrillConnectionImpl.java:186)
	at org.apache.calcite.avatica.AvaticaStatement.executeInternal(AvaticaStatement.java:156)
	at org.apache.calcite.avatica.AvaticaStatement.execute(AvaticaStatement.java:217)
	at sqlline.Commands.executeSingleQuery(Commands.java:1054)
	at sqlline.Commands.execute(Commands.java:1003)
	at sqlline.Commands.sql(Commands.java:967)
	at sqlline.SqlLine.dispatch(SqlLine.java:734)
	at sqlline.SqlLine.begin(SqlLine.java:541)
	at sqlline.SqlLine.start(SqlLine.java:267)
	at sqlline.SqlLine.main(SqlLine.java:206)
Caused by: org.apache.drill.common.exceptions.UserRemoteException: EXECUTION_ERROR ERROR: Could not initialize class com.github.pjfanning.xlsx.impl.StreamingWorkbookReader
```

**Comment by pjfanning** [comment] 2021-11-12 19:27
One change in v3.2.0 is that StreamingWorkbookReader creates an XmlInputFactory as a static instance - to avoid creating many factory instances over JVM lifetime.

I can do a v3.2.2 release where this is avoided - I can try to create the XmlInputFactory later while still having a shared instance.

**Comment by cgivre** [comment] 2021-11-12 19:31
That would be perfect.

**Comment by pjfanning** [comment] 2021-11-12 20:06
@cgivre would you be able to test with 3.2.2-SNAPSHOT (which has a change in it)? - if not I can release it as 3.2.2

**Comment by cgivre** [comment] 2021-11-12 20:25
I’ll give it a go this weekend.  Thanks for your quick response!

**Comment by pjfanning** [comment] 2021-11-12 21:39
@cgivre I published v3.2.3 which includes the v3.2.2 change mentioned above and another issue that won't affect Drill (relating to serializing comments when an optional feature is enabled).

**Comment by pjfanning** [comment] 2021-11-13 12:18
Releases are tested by using them in this sample: https://github.com/pjfanning/excel-streaming-reader-sample

They are not tested in Hadoop deployments though.

So the issue appears to be something specific to running within a Hadoop setup.

Other than the static XMLInputFactory change that was modified in v3.2.2, the other big change in excel-streaming-reader 3.2.x is the use of Apache POI 5.1.0 - which has a few dependency changes of its own and some internal changes too.

In the end, if needs be, Apache Drill could revert back to an older version of excel-streaming-reader. I'd prefer to get this sorted out but if fixing the Apache Drill Excel problems is urgent, then reverting Apache Drill upgrade of excel-streaming-reader is an option.

**Comment by cgivre** [comment] 2021-11-13 23:35
@pjfanning I'm doing some digging, but this seems like it actually might be related to a logging issue in POI.   Stand by.

**Comment by pjfanning** [comment] 2021-11-13 23:41
POI 5.1.0 switched to log4j 2.x for logging

**Comment by cgivre** [comment] 2021-11-13 23:57
This is where my knowledge of java/maven starts to suck.  I'm wondering if it's possible to somehow exclude the logger from POI.  

I'm surprised this didn't get caught in someone's unit tests.  Anyway, unless you have any other suggestion, I'm going to have to revert the update for the time being.

**Comment by pjfanning** [comment] 2021-11-14 00:03
POI creates static logger instances in a large proportion of its classes - so POI will not work with log4j-api jar on classpath.

**Comment by pjfanning** [comment] 2021-11-14 00:08
if you add this dependency jar, log4j will log to slf4j - (POI 5.0.0 used slf4j loggers) - 'org.apache.logging.log4j:log4j-to-slf4j:2.14.1'

**Comment by cgivre** [comment] 2021-11-14 00:43
Well progress?    I added that dependency to the module, and got the following stack trace below.

I wonder if I should add that dependency at the root level pom?  It's amazing how logging can cause so many headaches.

```java
  (java.lang.NoSuchMethodError) org.apache.logging.log4j.util.Strings.isEmpty(Ljava/lang/CharSequence;)Z
    org.apache.logging.log4j.status.StatusLogger.<init>():107
    org.apache.logging.log4j.status.StatusLogger.<clinit>():85
    org.apache.logging.log4j.LogManager.<clinit>():61
    org.apache.poi.openxml4j.opc.OPCPackage.<clinit>():73
    com.github.pjfanning.xlsx.impl.StreamingWorkbookReader.init():118
    com.github.pjfanning.xlsx.impl.StreamingWorkbookReader.init():96
    com.github.pjfanning.xlsx.StreamingReader$Builder.open():373
    org.apache.drill.exec.store.excel.ExcelBatchReader.openFile():232
    org.apache.drill.exec.store.excel.ExcelBatchReader.open():196
    org.apache.drill.exec.store.excel.ExcelBatchReader.open():62
    org.apache.drill.exec.physical.impl.scan.framework.ManagedScanFramework.open():208
    org.apache.drill.exec.physical.impl.scan.file.FileScanFramework.open():276
    org.apache.drill.exec.physical.impl.scan.framework.ShimBatchReader.open():75
    org.apache.drill.exec.physical.impl.scan.ReaderState.open():229
    org.apache.drill.exec.physical.impl.scan.ScanOperatorExec.nextAction():273
    org.apache.drill.exec.physical.impl.scan.ScanOperatorExec.next():229
    org.apache.drill.exec.physical.impl.protocol.OperatorDriver.doNext():201
    org.apache.drill.exec.physical.impl.protocol.OperatorDriver.start():179
    org.apache.drill.exec.physical.impl.protocol.OperatorDriver.next():129
    org.apache.drill.exec.physical.impl.protocol.OperatorRecordBatch.next():149
    org.apache.drill.exec.record.AbstractRecordBatch.next():119
    org.apache.drill.exec.record.AbstractRecordBatch.next():111
    org.apache.drill.exec.record.AbstractUnaryRecordBatch.innerNext():59
    org.apache.drill.exec.physical.impl.limit.LimitRecordBatch.innerNext():93
    org.apache.drill.exec.record.AbstractRecordBatch.next():170
    org.apache.drill.exec.record.AbstractRecordBatch.next():119
    org.apache.drill.exec.record.AbstractRecordBatch.next():111
    org.apache.drill.exec.record.AbstractUnaryRecordBatch.innerNext():59
    org.apache.drill.exec.record.AbstractRecordBatch.next():170
    org.apache.drill.exec.record.AbstractRecordBatch.next():119
    org.apache.drill.exec.record.AbstractRecordBatch.next():111
    org.apache.drill.exec.record.AbstractUnaryRecordBatch.innerNext():59
    org.apache.drill.exec.physical.impl.project.ProjectRecordBatch.innerNext():85
    org.apache.drill.exec.record.AbstractRecordBatch.next():170
    org.apache.drill.exec.physical.impl.BaseRootExec.next():103
    org.apache.drill.exec.physical.impl.ScreenCreator$ScreenRoot.innerNext():81
    org.apache.drill.exec.physical.impl.BaseRootExec.next():93
    org.apache.drill.exec.work.fragment.FragmentExecutor$1.run():323
    org.apache.drill.exec.work.fragment.FragmentExecutor$1.run():310
    java.security.AccessController.doPrivileged():-2
    javax.security.auth.Subject.doAs():422
    org.apache.hadoop.security.UserGroupInformation.doAs():1762
    org.apache.drill.exec.work.fragment.FragmentExecutor.run():310
    org.apache.drill.common.SelfCleaningRunnable.run():38
    java.util.concurrent.ThreadPoolExecutor.runWorker():1149
    java.util.concurrent.ThreadPoolExecutor$Worker.run():624
    java.lang.Thread.run():748 (state=,code=0)
```

**Comment by cgivre** [comment] 2021-11-14 00:43
Thanks again for your help and quick responses BTW!

**Comment by pjfanning** [comment] 2021-11-14 12:15
@cgivre org.apache.logging.log4j.util.Strings - despite its class name is actually an Apache Drill class - see https://github.com/apache/drill/blob/master/contrib/storage-hive/core/src/main/java/org/apache/logging/log4j/util/Strings.java

This seems to be built with an older version of log4j and causes compatibility issues when POI tries to use the latest version of log4j.

**Comment by pjfanning** [comment] 2021-11-14 12:50
@cgivre I raised https://github.com/apache/drill/issues/2373

**Comment by vvysotskyi** [comment] 2021-11-14 18:45
@pjfanning, Apache Drill don't and shouldn't have a dependency on log4j. 
`org.apache.logging.log4j.util.Strings` class was introduced as a workaround before https://issues.apache.org/jira/browse/HIVE-23088 will be resolved and we will use version with that fix.

Is it possible in this project also remove usage of log4j string utils and use for example a method from commons or something like that?

**Comment by pjfanning** [comment] 2021-11-14 18:47
@vvysotskyi the log4j dependency is not in this project - it is in Apache POI, a transitive dependency of this project

**Comment by pjfanning** [comment] 2021-11-14 18:48
@vvysotskyi Apache Hive haven't done a release in 2 years - I wouldn't hold my breath waiting for them to release the fix

**Comment by vvysotskyi** [comment] 2021-11-14 18:52
@pjfanning, in this case as a workaround for Drill we can update the copy of that class, but shouldn't introduce library as a direct dependency.
Also, as a long-term solution, it would be good to create a ticket for Apache POI to remove direct dependencies in the code on the specific logger implementation.

**Comment by pjfanning** [comment] 2021-11-15 14:14
moving to https://issues.apache.org/jira/browse/DRILL-8044

**Closed by pjfanning** 2021-11-15 14:14 UTC
