### ISSUE TITLE
Set rowcacheSize(100) error！

### ISSUE THREAD

**Issue by yimengfan** [pjfanning/excel-streaming-reader#239] opened 2024-02-06 11:06 UTC
The excel size ：9M 
Set rowCacheSize(100) error, set to 10 will success!
![image](https://github.com/pjfanning/excel-streaming-reader/assets/26621257/3019804e-e2ab-4ca0-8697-584a79089539)

**Comment by pjfanning** [comment] 2024-02-08 16:23
I don't know what this issue is about. Can you provide a reproducible test case?

**Comment by pjfanning** [comment] 2024-03-26 11:45
closing due to lack of anything to investigate

**Closed by pjfanning** 2024-03-26 11:45 UTC
